### ISSUE TITLE
Grow/shrink selection tool

### ISSUE THREAD

**Issue by mestaritonttu** [pasbi/ommpfritt#67] opened 2019-06-22 11:06 UTC
Hey, this is amazing - you are implementing a concept I started dreaming about 3 years ago. In my view you are starting a small (?) revolution. I hope your work can act as a reference for other FOSS 2D vector tools.

Looking at my old notes, I was mostly focusing on selection and point manipulation workflows. I feel having a robust and powerful selection toolbox will allow artists to work quickly and without effort. I was looking at Modo as a reference point as that is what I knew from my old 3D graphics days as having the best workflows regarding this area.

Would it be OK for you, if I open feature requests along these lines?

**Grow/shrink tool**

Expand or contract the current point selection uniformly. If you have separate selections, they will all grow or shrink at the same time.

**Comment by pasbi** [comment] 2019-06-24 08:12
Hi, you're very welcome to issue feature requests and bugs here, that's exactly what this section is meant for ;)

I appreciate your interest very much. If you'd like to discuss I recommend you to join the irc chat `#omm-devel`.


There is already a tool to select points and to scale that very selection. I'm not quite sure if I got your feature request right: you want to scale separate continuous selections of a path wrt. their particular center?



![selection](https://user-images.githubusercontent.com/4587007/60002208-85f98c00-9668-11e9-8585-1a080c8f1079.gif)

**Comment by mestaritonttu** [comment] 2019-06-24 08:45
Ah, sorry for being unclear: the feature is not about transformation, but about adding or subtracting points :) So the number of selected points grows or shrinks in both directions.

**Comment by pasbi** [comment] 2019-06-24 08:52
That should be trivial to implement.
I don't see it as very urgent, as for 1D-objects like paths it's trivial to grow/shrink the selection manually (at most two points per part). I can, however, see some nice use-cases for that together with other (future) tools. 
Do you want to implement it? For me it has quite low priority, unfortunately (see #68).

**Comment by mestaritonttu** [comment] 2019-06-24 09:08
No worry about the urgency. I am just happy to log these and know that you care! Unfortunately I don't have the C++ skills to implement it (yet). I do have lots of experience in recruiting contributors, though. We can discuss more later in the chat.

**Comment by pasbi** [comment] 2020-07-09 21:38
fixed in 5d38f622f52b44ffa67cc531ff406b8121856d5f

**Closed by pasbi** 2020-07-09 21:38 UTC

**Comment by mestaritonttu** [comment] 2020-07-15 04:57
@pasbi is it expected that I can't see this in the UI yet?

**Comment by pasbi** [comment] 2020-07-15 07:21
Actually, it is expected. However, it's not supposed to be invisible.
The problem is, that I haven't adapted the default layout.
For a quick test, you can add the action to a toolbar: click on the `E` at the left/bottom end of any toolbar to show the tool-bar-configuration-dialog.

If you have the time, you may want to come up with a more sensible default toolbar layout and overwrite the file `ommpfritt/layouts/default_layout.ini`.

You may also want to add the action into some menu, but you edit the `cpp`-code for that. Have a look at
`std::vector<QString> MainWindow::path_menu_entries()`
in `mainwindow.cpp`.

I appreciate your efforts :rocket:
